### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-zs6567xh/ast/AST/README'

### ISSUE THREAD

**Issue by Masquerade0097** [berkerpeksag/astor#122]
The following log is obtained when installing astor in docker.

`Step 23/40 : RUN pip3 install ast
 ---> Running in 5d999648aec0
Collecting ast
  Downloading https://files.pythonhosted.org/packages/4b/fb/2b954d2a38c9a0ef1da6a46737a75b4dbf6f60e5dad0f267a4ec5ece20de/AST-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zs6567xh/ast/setup.py", line 6, in <module>
        README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-zs6567xh/ast/AST/README'

`

**Comment by Masquerade0097** [comment]
@berkerpeksag
