### ISSUE TITLE
AttributeError: 'str' object has no attribute '__code__'

### ISSUE THREAD

**Issue by zaoqi** [berkerpeksag/astor#148]
```
>>> astor.code_to_ast('a={}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zaoqi/.local/lib/python3.7/site-packages/astor/file_util.py", line 98, in __call__
    key = self.get_file_info(codeobj)
  File "/home/zaoqi/.local/lib/python3.7/site-packages/astor/file_util.py", line 87, in get_file_info
    func_code = codeobj.__code__
AttributeError: 'str' object has no attribute '__code__'
```

**Comment by berkerpeksag** [comment]
Thank you for your report. As "code" in `code_to_ast()` implies, it expects a code object instead of a str object. However, I'd be happy to improve [`code_to_ast()` documentation](https://astor.readthedocs.io/en/latest/#astor.code_to_ast) and exception message. Feel free to share your suggestions!
