### ISSUE TITLE
Unable to install with setuptools==41.4.0

### ISSUE THREAD

**Issue by jonringer** [berkerpeksag/astor#162]
This package is unable to install with the `setup(**config['options'])` convention

```
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 17, in <module>
    setup(**config['options'])
  File "/nix/store/xhnwngvvrvsjw62ryafxhdk80wc00bj8-python3.7-setuptools-41.4.0/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/4g2ilwnk4mj4g68rc52kygx7gcqxnjd0-python3-3.7.5/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/nix/store/xhnwngvvrvsjw62ryafxhdk80wc00bj8-python3.7-setuptools-41.4.0/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/nix/store/4g2ilwnk4mj4g68rc52kygx7gcqxnjd0-python3-3.7.5/lib/python3.7/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/nix/store/xhnwngvvrvsjw62ryafxhdk80wc00bj8-python3.7-setuptools-41.4.0/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "/nix/store/xhnwngvvrvsjw62ryafxhdk80wc00bj8-python3.7-setuptools-41.4.0/lib/python3.7/site-packages/setuptools/dist.py", line 291, in check_specifier
    packaging.specifiers.SpecifierSet(value)
  File "/nix/store/xhnwngvvrvsjw62ryafxhdk80wc00bj8-python3.7-setuptools-41.4.0/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 594, in __init__
    specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
AttributeError: 'SpecifierSet' object has no attribute 'split'
```

see https://github.com/pypa/setuptools/issues/1869

**Comment by archenroot** [comment]
I observed with following versions:
dev-python/astor-0.7.1::gentoo
dev-python/setuptools-41.5.1

Is there any working combination?
