### ISSUE TITLE
test_try_expect fails with Python 3.5

### ISSUE THREAD

**Issue by felixonmars** [berkerpeksag/astor#48]
Not sure if it's introduced by Python 3.5, though. Hope it helps:

```
.....E.
======================================================================
ERROR: test_try_expect (tests.test_codegen.CodegenTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-astor/src/astor/tests/test_codegen.py", line 47, in test_try_expect
    self.assertAstSourceEqual(source)
  File "/build/python-astor/src/astor/tests/test_codegen.py", line 24, in assertAstSourceEqual
    self.assertEqual(astor.to_source(ast.parse(source)), source)
  File "/build/python-astor/src/astor/astor/codegen.py", line 40, in to_source
    generator.visit(node)
  File "/build/python-astor/src/astor/astor/misc.py", line 161, in visit
    return visitor(node)
  File "/build/python-astor/src/astor/astor/codegen.py", line 493, in visit_Module
    self.visit(stmt)
  File "/build/python-astor/src/astor/astor/misc.py", line 161, in visit
    return visitor(node)
  File "/build/python-astor/src/astor/astor/codegen.py", line 288, in visit_Try
    self.visit(handler)
  File "/build/python-astor/src/astor/astor/misc.py", line 161, in visit
    return visitor(node)
  File "/build/python-astor/src/astor/astor/codegen.py", line 300, in visit_ExceptHandler
    self.body(node.body)
  File "/build/python-astor/src/astor/astor/codegen.py", line 99, in body
    self.visit(stmt)
  File "/build/python-astor/src/astor/astor/misc.py", line 161, in visit
    return visitor(node)
  File "/build/python-astor/src/astor/astor/codegen.py", line 179, in visit_Expr
    self.generic_visit(node)
  File "/usr/lib/python3.5/ast.py", line 255, in generic_visit
    self.visit(value)
  File "/build/python-astor/src/astor/astor/misc.py", line 161, in visit
    return visitor(node)
  File "/build/python-astor/src/astor/astor/codegen.py", line 366, in visit_Call
    self.conditional_write(write_comma, '*', node.starargs)
AttributeError: 'Call' object has no attribute 'starargs'

----------------------------------------------------------------------
Ran 7 tests in 0.012s

FAILED (errors=1)
```

**Comment by kirbyfan64** [comment]
Has this been fixed in master? The test passes for me.

**Comment by berkerpeksag** [comment]
I don't think we did anything in master to fix this. Perhaps something had changed in Python? It would be nice to do some detective work :)

**Comment by felixonmars** [comment]
The same error is still present here for Python 3.6 :(

**Comment by pmaupin** [comment]
I thought I fixed this in trunk in May 2015 974d7a2d6baa607d774601c01e02e6489e9ca54a

**Comment by felixonmars** [comment]
Oops, sorry. The test was invalid and it actually passes in Python 3.6. Thanks a lot! Hope there will be a release soon.

**Comment by berkerpeksag** [comment]
Yay! Closing this then.
